#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Aliases
alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias term='itermocil'
alias pyserver='python -m SimpleHTTPServer 9000'
alias weather='curl -4 wttr.in/Greenville'
alias yolo='git push origin master && git push heroku master'
alias dot='~/.dotfiles'
alias cpwd='cd $pwd'
alias chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'

# Git Shortcuts
alias gp="git push origin"
alias gc="git commit"
alias ga="git add ."
alias gs="git status"
alias log="git log"

# Exports
export FABRIC_API_KEY=832b942c034afd6e4772120ba045e88211a693ba
export FABRIC_API_SECRET=042d41e897f444a5d31c47d933496f142302ee4cf6aa1f6a1897b2f12ced6f5f

# Waiting Dots
COMPLETION_WAITING_DOTS="true"

# The Rubies
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
