#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Aliases
alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias term='itermocil'
alias pyserver='python -m SimpleHTTPServer 9000'
alias weather='curl -4 wttr.in/Atlanta'
alias v='vim .'
alias yolo='git push origin master && git push heroku master'
alias dot='~/.dotfiles'
alias nodebp='. ~/.node_boilerplate/script.sh'
alias cpwd='cd $pwd'
alias google-chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'
alias tiyd='sh ~/tiy_dir.sh'

# Git Shortcuts
alias gp="git push origin"
alias gc="git commit"
alias ga="git add ."
alias gs="git status"

# Waiting Dots
COMPLETION_WAITING_DOTS="true"

# The Rubies
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# Iron Yard Specific Stuff
alias iron='~/TheIronYard'
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(newline_hw init)"
